# This controller was generated by RailsPanel generator. Remember to include RailsPanel::Resources in thi class
# or in this class superclass
class AuthorsController < ApplicationController
  respond_to :json, :only => :index

  def resources
    if params[:format] == 'json'
       Author.where("name like ?", "%#{params[:q]}%")
    else
      super
    end
  end
end

